source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

inhibit_all_warnings!
use_frameworks!

target 'victorious' do
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'KVOController', '~> 1.2.0'
    pod 'SDWebImage', '~> 3.8.2'
    pod 'CCHLinkTextView', '~> 1.2.0'
    pod 'FBSDKCoreKit', '~> 4.16.0'
    pod 'FBSDKLoginKit', '~> 4.16.1'
    pod 'FBSDKShareKit', '~> 4.16.1'
    pod 'FLAnimatedImage', '~> 1.0'
    pod 'Reveal-SDK', :configurations => ['Debug']

    target 'victoriousTests' do
        inherit! :search_paths
        pod 'Nocilla', :git => 'https://github.com/TouchFrame/Nocilla.git'
        pod 'OCMock', '~> 3.3.1'
    end

    target 'VictoriousCommonTests' do
        inherit! :search_paths
        pod 'Nocilla', :git => 'https://github.com/TouchFrame/Nocilla.git'
        pod 'OCMock', '~> 3.3.1'
    end

end

target 'VictoriousIOSSDKTests' do
    pod 'Nocilla', :git => 'https://github.com/TouchFrame/Nocilla.git'
end

target 'victoriousPersistenceTests' do
    pod 'Nocilla', :git => 'https://github.com/TouchFrame/Nocilla.git'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            if config.name == "QA" || config.name == "Staging" || config.name == "Stable" then
                config.build_settings['CODE_SIGN_IDENTITY[sdk=iphoneos*]'] = 'iPhone Distribution'
            end
        end
    end
end
