source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.1'

inhibit_all_warnings!
use_frameworks!

target :victorious do
    pod 'RestKit', '0.25.0'
    pod 'TTTAttributedLabel'
    pod 'MBProgressHUD'
    pod 'KVOController'
    pod 'SDWebImage'
    pod 'CCHLinkTextView'
    pod 'OAStackView'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'CHTCollectionViewWaterfallLayout'
    pod 'youtube-ios-player-helper'
    link_with 'victorious'

    target :test do
        pod 'Nocilla', :git => 'https://github.com/TouchFrame/Nocilla.git'
        link_with 'victoriousTests', 'VictoriousCommonTests'
    end
end

target 'UIAutomationTests', :exclusive => true do
  pod 'KIF', :git => 'https://github.com/TouchFrame/KIF.git'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            if config.name == "QA" || config.name == "Staging" || config.name == "Stable" then
                config.build_settings['CODE_SIGN_IDENTITY[sdk=iphoneos*]'] = 'iPhone Distribution'
            end
        end
    end
end
