source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.1'

inhibit_all_warnings!

target :victorious do
    pod 'RestKit'
    pod 'TTTAttributedLabel'
    pod 'MBProgressHUD'
    pod 'FlurrySDK'
    pod 'KVOController'
    pod 'SDWebImage'
    pod 'CCHLinkTextView'
    pod 'OAStackView'
    link_with 'victorious'

    target :test do
        pod 'Nocilla', :git => 'https://github.com/TouchFrame/Nocilla.git', :branch => 'block-response'
        link_with 'victoriousTests'
    end
end

target :VictoriousCommon do
    pod 'IGDigest'
    link_with 'VictoriousCommon'
end

target :VictoriousCommonOSX do
    platform :osx, "10.10"
    pod 'IGDigest'
    link_with 'VictoriousCommonOSX'
end
