source 'https://rubygems.org'

gem 'activesupport', require: false
gem 'httparty',      require: false

group :test do
  gem 'minitest'
  gem 'guard'
  gem 'guard-minitest'
  gem 'guard-bundler'
  gem 'minitest-rg'
end
