//
//  VStreamCollectionViewDataSource.h
//  victorious
//
//  Created by Will Long on 9/8/14.
//  Copyright (c) 2014 Victorious. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "VAbstractFilter+RestKit.h"

extern NSString *const VStreamCollectionDataSourceDidChangeNotification;

@class  VStream, VStreamItem, VStreamCollectionViewDataSource;

/**
 *  Data delegate for the VStreamCollectionViewDataSource.
 */
@protocol VStreamCollectionDataDelegate <NSObject>

@required
/**
 *  Fetches a UICollectionViewCell for a VStreamItem
 *
 *  @param dataSource the dataSource requesting a cell
 *  @param streamItem The VStreamItem object that needs to be displayed
 *
 *  @return an appropriate UICollectionViewCell for the given streamItem
 */
- (UICollectionViewCell *)dataSource:(VStreamCollectionViewDataSource *)dataSource cellForIndexPath:(NSIndexPath *)indexPath;

@optional

/**
 *  Notifies the data delgate that the datasource has received new stream
 *  items and it should prepare to display cells for each of the stream items.
 */
- (void)dataSource:(VStreamCollectionViewDataSource *)dataSource
 hasNewStreamItems:(NSArray *)streamItems;

/**
 *  Allows a view controller implementation to specify if conditions of the calling code
 *  context required that an activity indivator footer view be generated by the data source
 *  and shown in the collection view.
 *
 *  @return YES to create and supply the footer the collection view, or NO if footer is not required.
 */
- (BOOL)shouldDisplayActivityViewFooterForCollectionView:(UICollectionView *)collectionView inSection:(NSInteger)section;

@end

@interface VStreamCollectionViewDataSource : NSObject <UICollectionViewDataSource>

@property (nonatomic, weak) id<VStreamCollectionDataDelegate> delegate;
@property (nonatomic, weak) UICollectionView *collectionView; ///< The UICollectionView object to which the receiver is providing data
@property (nonatomic, strong) VStream *stream;///< The stream object used to populate the collectionView
@property (nonatomic) BOOL hasHeaderCell;///<If set to YES it will insert a section at index 0 with 1 row for the Marquee stream.

/**
 *  Initializes the data source with a default stream.
 *
 *  @param stream The stream used to populate the data source
 *
 *  @return A VStreamCollectionViewDataSource
 */
- (instancetype)initWithStream:(VStream *)stream;

/**
 *  Returns the VStreamItem location at the index path in the stream
 *
 *  @param indexPath The location of the index path
 *
 *  @return a VStreamItem in self.stream
 */
- (VStreamItem *)itemAtIndexPath:(NSIndexPath *)indexPath;

/**
 *  Returns the index path of a streamItem
 *
 *  @param streamItem A VstreamItem
 *
 *  @return The IndexPath of the streamItem in self.stream
 */
- (NSIndexPath *)indexPathForItem:(VStreamItem *)streamItem;


/**
 *  The primary way to load a stream.
 *
 *  @param pageType Which page of this paginatined method should be loaded.  @see VPageType
 */
- (void)loadPage:(VPageType)pageType withSuccess:(void (^)(void))successBlock failure:(void (^)(NSError *))failureBlock;

- (NSUInteger)count; ///< Number of VStreamItems in self.stream
- (BOOL)isFilterLoading; ///< Returns YES if the filter is currently being loaded from the server
- (BOOL)canLoadNextPage; ///< Returns whether or not there is a nother page to load, i.e. we are not already at the end of the stream.
- (NSInteger)sectionIndexForContent; ///< Returns either 0 or 1 depending on whether a header cell is present
- (void)unloadStream;

@end
