FASTLANE_DIRECTORY = File.dirname(__FILE__)
$LOAD_PATH.unshift(FASTLANE_DIRECTORY + '/lib')
require 'vams'

# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.36.0"

default_platform :ios

def apply_config(build_name:, environment:)
  sh "cd ../../ && ./build-scripts/apply-config.sh #{build_name} -e #{environment}"
end

def prepare_metadata(client:, build_name:)
  app_with_meta = client.app_by_build_name(build_name)
  metadata      = VAMS::Metadata.new(app_with_meta)
  metadata_path = File.join(FASTLANE_DIRECTORY, 'metadata')
  metadata.save(location: metadata_path, language: 'en-US')
  app_with_meta
end

def with_bundle_id(bundle_id:)
  old_bundle_id = ENV['BUNDLE_ID']
  ENV['BUNDLE_ID'] = bundle_id
  yield
  ENV['BUNDLE_ID'] = old_bundle_id
end

def clean_build_products
  clean_build_artifacts
  `git checkout #{FASTLANE_DIRECTORY}/../AppSpecific`
  `git checkout #{FASTLANE_DIRECTORY}/../fastlane/metadata/`
end

def make_build_string(version:, build_number:)
  "#{version} (#{build_number})"
end

def send_submission_result(app_id:, client:, build:, status:)
  result = VAMS::SubmissionResult.new(
    app_id:   app_id,
    datetime: Time.now,
    build:    build,
    status:   status
  )
  client.submit_result(result)
end

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods

    # increment_build_number

    # xctool # run the tests of your app
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do |options|
    ensure_git_status_clean unless ENV['IGNORE_DIRTY_GIT_STATE']
    environment = options[:environment]
    client      = VAMS::Client.new(environment: environment || :production)
    client.apps_to_build.each do |app|
      clean_build_products

      logger       = VAMS::ColoredLogger.new($stdout)
      version      = ''
      build_number = ''

      begin
        apply_config(build_name: app.build_name, environment: environment)
        app_with_meta = prepare_metadata(client: client, build_name: app.build_name)

        with_bundle_id(bundle_id: app_with_meta.sanitized_bundle_id) do
          sigh

          gym(
            scheme:               'release-victorious',
            codesigning_identity: 'iPhone Distribution: Victorious Inc. (82T26U698A)',
          )
          version      = get_version_number(xcodeproj: 'victorious.xcodeproj')
          build_number = get_build_number(xcodeproj:   'victorious.xcodeproj')

          # HACK: This is a workaround the fact that spaceship uses a different environment variable for logging in iTunesConnect.
          #       We'll need to keep an eye on it. It will prrobably break in the future.
          ENV['FASTLANE_ITC_TEAM_ID']   = ENV['FASTLANE_TEAM_ID']
          ENV['FASTLANE_ITC_TEAM_NAME'] = ENV['FASTLANE_TEAM_NAME']

          deliver(force: true)

          status = VAMS::SubmissionResult::Status::GOOD
          send_submission_result(app_id: app.app_id,
                                 client: client,
                                 build:  make_build_string(version:      version,
                                                           build_number: build_number),
                                 status: status)
          logger.info("Notified VAMS with status: #{status}")
        end

      rescue Exception => exception
        status = VAMS::SubmissionResult::Status::BAD
        logger.error(exception.message)
        logger.error(exception.backtrace.join("\n"))
        send_submission_result(app_id: app.app_id,
                               client: client,
                               build:  make_build_string(version:      version,
                                                         build_number: build_number),
                               status: status)
        logger.error("Notified VAMS with status: #{status}")
      ensure
        clean_build_products
      end
    end
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
