source 'https://rubygems.org'

gem 'activesupport', require: false
gem 'httparty'
gem 'dotenv'

group :test do
  gem 'minitest'
  gem 'guard'
  gem 'guard-minitest'
  gem 'guard-bundler'
  gem 'minitest-rg'
  gem 'webmock'
end
