source 'https://rubygems.org'

gem 'activesupport', require: false
gem 'httparty'
gem 'dotenv'
gem 'colorize'
gem 'fastlane'
gem 'temporary_environment'

group :development do
  gem 'pry', require: false
end

group :test do
  gem 'minitest'
  gem 'guard'
  gem 'guard-minitest'
  gem 'guard-bundler'
  gem 'minitest-rg'
  gem 'webmock'
  gem 'fakefs', require: false
end
