require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << 'test'
  t.test_files = FileList['test/**/*_test.rb'] << 'test/smoke_test_vams_api.rb'
end

task :console do
  $LOAD_PATH.unshift('lib')
  require 'vams'
  require 'pry'
  binding.pry
end

task default: :test
